model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo  # 使用openai前缀- model_name: openai/gpt-3.5-turbo
      api_base: "https://api.chatanywhere.tech/v1"
      api_key: "sk-BsRMeQwcicufLZL2sJj1c6Db2udoCIjB89EZEHRHD41sH256"